// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: proto/poll.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "poll.v1";

export interface ValidatePollRequest {
  pollId: string;
}

export interface ValidatePollResponse {
  isValid: boolean;
  reason: ValidatePollResponse_ValidityReason;
  expiredAt: Timestamp | undefined;
}

export enum ValidatePollResponse_ValidityReason {
  REASON_UNSPECIFIED = 0,
  OK = 1,
  POLL_NOT_FOUND = 2,
  POLL_EXPIRED = 3,
  POLL_NOT_STARTED = 4,
  POLL_CLOSED = 5,
  UNRECOGNIZED = -1,
}

export const POLL_V1_PACKAGE_NAME = "poll.v1";

export interface PollServiceClient {
  validatePollForVoting(request: ValidatePollRequest): Observable<ValidatePollResponse>;
}

export interface PollServiceController {
  validatePollForVoting(
    request: ValidatePollRequest,
  ): Promise<ValidatePollResponse> | Observable<ValidatePollResponse> | ValidatePollResponse;
}

export function PollServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["validatePollForVoting"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PollService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PollService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POLL_SERVICE_NAME = "PollService";
