// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/poll.proto

package pollv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatePollResponse_ValidityReason int32

const (
	ValidatePollResponse_REASON_UNSPECIFIED ValidatePollResponse_ValidityReason = 0
	ValidatePollResponse_OK                 ValidatePollResponse_ValidityReason = 1
	ValidatePollResponse_POLL_NOT_FOUND     ValidatePollResponse_ValidityReason = 2
	ValidatePollResponse_POLL_EXPIRED       ValidatePollResponse_ValidityReason = 3
	ValidatePollResponse_POLL_NOT_STARTED   ValidatePollResponse_ValidityReason = 4
	ValidatePollResponse_POLL_CLOSED        ValidatePollResponse_ValidityReason = 5
)

// Enum value maps for ValidatePollResponse_ValidityReason.
var (
	ValidatePollResponse_ValidityReason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "OK",
		2: "POLL_NOT_FOUND",
		3: "POLL_EXPIRED",
		4: "POLL_NOT_STARTED",
		5: "POLL_CLOSED",
	}
	ValidatePollResponse_ValidityReason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"OK":                 1,
		"POLL_NOT_FOUND":     2,
		"POLL_EXPIRED":       3,
		"POLL_NOT_STARTED":   4,
		"POLL_CLOSED":        5,
	}
)

func (x ValidatePollResponse_ValidityReason) Enum() *ValidatePollResponse_ValidityReason {
	p := new(ValidatePollResponse_ValidityReason)
	*p = x
	return p
}

func (x ValidatePollResponse_ValidityReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidatePollResponse_ValidityReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_poll_proto_enumTypes[0].Descriptor()
}

func (ValidatePollResponse_ValidityReason) Type() protoreflect.EnumType {
	return &file_proto_poll_proto_enumTypes[0]
}

func (x ValidatePollResponse_ValidityReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidatePollResponse_ValidityReason.Descriptor instead.
func (ValidatePollResponse_ValidityReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_poll_proto_rawDescGZIP(), []int{1, 0}
}

type ValidatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePollRequest) Reset() {
	*x = ValidatePollRequest{}
	mi := &file_proto_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePollRequest) ProtoMessage() {}

func (x *ValidatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePollRequest.ProtoReflect.Descriptor instead.
func (*ValidatePollRequest) Descriptor() ([]byte, []int) {
	return file_proto_poll_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatePollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type ValidatePollResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	IsValid       bool                                `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason        ValidatePollResponse_ValidityReason `protobuf:"varint,2,opt,name=reason,proto3,enum=poll.v1.ValidatePollResponse_ValidityReason" json:"reason,omitempty"`
	ExpiredAt     *timestamppb.Timestamp              `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePollResponse) Reset() {
	*x = ValidatePollResponse{}
	mi := &file_proto_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePollResponse) ProtoMessage() {}

func (x *ValidatePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePollResponse.ProtoReflect.Descriptor instead.
func (*ValidatePollResponse) Descriptor() ([]byte, []int) {
	return file_proto_poll_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatePollResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidatePollResponse) GetReason() ValidatePollResponse_ValidityReason {
	if x != nil {
		return x.Reason
	}
	return ValidatePollResponse_REASON_UNSPECIFIED
}

func (x *ValidatePollResponse) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

var File_proto_poll_proto protoreflect.FileDescriptor

const file_proto_poll_proto_rawDesc = "" +
	"\n" +
	"\x10proto/poll.proto\x12\apoll.v1\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x13ValidatePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"\xb1\x02\n" +
	"\x14ValidatePollResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12D\n" +
	"\x06reason\x18\x02 \x01(\x0e2,.poll.v1.ValidatePollResponse.ValidityReasonR\x06reason\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"}\n" +
	"\x0eValidityReason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x12\n" +
	"\x0ePOLL_NOT_FOUND\x10\x02\x12\x10\n" +
	"\fPOLL_EXPIRED\x10\x03\x12\x14\n" +
	"\x10POLL_NOT_STARTED\x10\x04\x12\x0f\n" +
	"\vPOLL_CLOSED\x10\x052c\n" +
	"\vPollService\x12T\n" +
	"\x15ValidatePollForVoting\x12\x1c.poll.v1.ValidatePollRequest\x1a\x1d.poll.v1.ValidatePollResponseBLZJgithub.com/tim8912097887-sys/Poll-Maker/services/vote_service/proto/pollv1b\x06proto3"

var (
	file_proto_poll_proto_rawDescOnce sync.Once
	file_proto_poll_proto_rawDescData []byte
)

func file_proto_poll_proto_rawDescGZIP() []byte {
	file_proto_poll_proto_rawDescOnce.Do(func() {
		file_proto_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_poll_proto_rawDesc), len(file_proto_poll_proto_rawDesc)))
	})
	return file_proto_poll_proto_rawDescData
}

var file_proto_poll_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_poll_proto_goTypes = []any{
	(ValidatePollResponse_ValidityReason)(0), // 0: poll.v1.ValidatePollResponse.ValidityReason
	(*ValidatePollRequest)(nil),              // 1: poll.v1.ValidatePollRequest
	(*ValidatePollResponse)(nil),             // 2: poll.v1.ValidatePollResponse
	(*timestamppb.Timestamp)(nil),            // 3: google.protobuf.Timestamp
}
var file_proto_poll_proto_depIdxs = []int32{
	0, // 0: poll.v1.ValidatePollResponse.reason:type_name -> poll.v1.ValidatePollResponse.ValidityReason
	3, // 1: poll.v1.ValidatePollResponse.expired_at:type_name -> google.protobuf.Timestamp
	1, // 2: poll.v1.PollService.ValidatePollForVoting:input_type -> poll.v1.ValidatePollRequest
	2, // 3: poll.v1.PollService.ValidatePollForVoting:output_type -> poll.v1.ValidatePollResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_poll_proto_init() }
func file_proto_poll_proto_init() {
	if File_proto_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_poll_proto_rawDesc), len(file_proto_poll_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_poll_proto_goTypes,
		DependencyIndexes: file_proto_poll_proto_depIdxs,
		EnumInfos:         file_proto_poll_proto_enumTypes,
		MessageInfos:      file_proto_poll_proto_msgTypes,
	}.Build()
	File_proto_poll_proto = out.File
	file_proto_poll_proto_goTypes = nil
	file_proto_poll_proto_depIdxs = nil
}
