name: "Node Setup Action"
description: "Sets up PNPM and Node.js with caching"

inputs:
  node-version:
    required: true
  pnpm-version:
    required: true
  workdir:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.workdir }}/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: pnpm install --frozen-lockfile
