name: CI-Polls-Service-Integration-Test
on:
  pull_request:
    branches:
      - main
      - feat/**
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref != 'refs/heads/main' }}
jobs:
  polls-service-integration-test:
    environment:
      name: Poll Service
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      CACHE_SOCKET_TIMEOUT: ${{ vars.CACHE_SOCKET_TIMEOUT }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CACHE_URL: ${{ secrets.CACHE_URL }}
    defaults:
      run:
        working-directory: ./services/poll_service
    strategy:
      matrix:
        node-version: [22, 24]
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: polls_maker
        options: >-
          --health-cmd "pg_isready -U postgres -d polls_maker"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
      redis:
        image: redis:8.0-alpine
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 5s
      kafka-server:
        image: apache/kafka:4.3.0
        ports:
          - 9092:9092
          - 29092:29092
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093
          KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-server:9092,EXTERNAL://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        options: >-
          --health-cmd "bash -c 'nc -z localhost 9092'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 20s
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node and PNPM
        uses: ./.github/actions/node-setup
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: 10.26.1
          workdir: ./services/poll_service
      - name: Query Postgres inside Container
        env:
          PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          # Execute psql inside the container named 'postgres'
          docker exec -e PGPASSWORD="$PGPASSWORD" ${{ job.services.postgres.id }} psql -U postgres -d polls_maker -c "SELECT 1;"
      - name: Ping Redis
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          # Run redis-cli inside the container named 'redis'
          docker exec ${{ job.services.redis.id }} redis-cli -a "$REDIS_PASSWORD" ping
      - name: Create Kafka topic
        run: |
          docker exec ${{ job.services.kafka-server.id }} \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --create \
            --if-not-exists \
            --topic vote.created \
            --partitions 1 \
            --replication-factor 1
      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm db:migrate
      - name: Test
        run: pnpm test
